# Specify Base Image
FROM docker.io/node:18-alpine

# Work Directory
WORKDIR /usr/app

#Copy the package.json into workdir
COPY ./package.json ./

# Copy dev files into Container
COPY ./ ./

# Install Dependencies
RUN npm install

# Startup Command
CMD ["npm", "run", "serve"]
